#goal definition
geometry_msgs/Pose goal
#navigation mode: 0:直线导航 1:曲线导航 2:旋转调整姿态导航
uint32 navigation_mode
# 1 直线拟合  2 曲线拟合  3 或其他无效标志
uint8 navigation_path
---
#result definition
# Error codes
uint32 error_code
#错误码
uint32 NONE=0 #无异常
uint32 UNKNOWN=100
uint32 GOAL_OCCUPIED=101 #目标点被占用
uint32 TIMEOUT=102 #规划超时
uint32 NO_VALID_PATH=103 #无可通行路线
---
#feedback definition